import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { RootState } from './index';
import type { User } from '../types';

// ─── Types ────────────────────────────────────────────────────────────────────

interface AuthResponse {
  success: boolean;
  data: {
    user: User;
    accessToken: string;
    refreshToken: string;
  };
}

interface MeResponse {
  success: boolean;
  data: { user: User };
}

interface LoginRequest {
  email: string;
  password: string;
}

interface RegisterRequest {
  name: string;
  email: string;
  password: string;
}

interface RefreshResponse {
  success: boolean;
  data: { accessToken: string; refreshToken: string };
}

// ─── RTK Query Auth API ───────────────────────────────────────────────────────

export const authApiSlice = createApi({
  reducerPath: 'authApi',

  baseQuery: fetchBaseQuery({
    baseUrl: import.meta.env.VITE_API_URL,
    // Attach access token to every request automatically
    prepareHeaders: (headers, { getState }) => {
      const token = (getState() as RootState).auth.accessToken
        ?? localStorage.getItem('accessToken');
      if (token) {
        headers.set('Authorization', `Bearer ${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({

    // ── POST /auth/login ──────────────────────────────────────────────────────
    login: builder.mutation<AuthResponse, LoginRequest>({
      query: (credentials) => ({
        url: '/auth/login',
        method: 'POST',
        body: credentials,
      }),
      // Side effect: persist tokens after successful login
      onQueryStarted: async (_, { queryFulfilled }) => {
        try {
          const { data } = await queryFulfilled;
          localStorage.setItem('accessToken', data.data.accessToken);
          localStorage.setItem('refreshToken', data.data.refreshToken);
        } catch { /* error handled by component */ }
      },
    }),

    // ── POST /auth/register ───────────────────────────────────────────────────
    register: builder.mutation<AuthResponse, RegisterRequest>({
      query: (payload) => ({
        url: '/auth/register',
        method: 'POST',
        body: payload,
      }),
      onQueryStarted: async (_, { queryFulfilled }) => {
        try {
          const { data } = await queryFulfilled;
          localStorage.setItem('accessToken', data.data.accessToken);
          localStorage.setItem('refreshToken', data.data.refreshToken);
        } catch { /* error handled by component */ }
      },
    }),

    // ── POST /auth/logout ─────────────────────────────────────────────────────
    logout: builder.mutation<{ success: boolean }, { refreshToken?: string }>({
      query: (body) => ({
        url: '/auth/logout',
        method: 'POST',
        body,
      }),
      onQueryStarted: async (_, { queryFulfilled }) => {
        try {
          await queryFulfilled;
        } finally {
          // Always clear tokens even if request fails
          localStorage.removeItem('accessToken');
          localStorage.removeItem('refreshToken');
        }
      },
    }),

    // ── POST /auth/refresh ────────────────────────────────────────────────────
    refreshToken: builder.mutation<RefreshResponse, { refreshToken: string }>({
      query: (body) => ({
        url: '/auth/refresh',
        method: 'POST',
        body,
      }),
      onQueryStarted: async (_, { queryFulfilled }) => {
        try {
          const { data } = await queryFulfilled;
          localStorage.setItem('accessToken', data.data.accessToken);
          localStorage.setItem('refreshToken', data.data.refreshToken);
        } catch { /* handled */ }
      },
    }),

    // ── GET /auth/me ──────────────────────────────────────────────────────────
    getMe: builder.query<MeResponse, void>({
      query: () => '/auth/me',
    }),

    // ── PATCH /auth/me ────────────────────────────────────────────────────────
    updateProfile: builder.mutation<MeResponse, Partial<{ name: string; preferences: object }>>({
      query: (body) => ({
        url: '/auth/me',
        method: 'PATCH',
        body,
      }),
    }),

  }),
});

// ─── Export hooks (auto-generated by RTK Query) ───────────────────────────────

export const {
  useLoginMutation,
  useRegisterMutation,
  useLogoutMutation,
  useRefreshTokenMutation,
  useGetMeQuery,
  useUpdateProfileMutation,
} = authApiSlice;